
version: "3.3"
services:

  sistemasapp:
    image: sistemasweb:latest
    ports:
      - "8887:8887"

  frontapp:
    image: frontweb:1.0
    ports:
      - "5000:80" 
    depends_on:
      - sistemasapp
