
version: "3.3"
services:

  sistemasapp:
    image: pablogivi/sistemasweb:1.0
    ports:
      - "8887:8887"

  frontapp:
    image: pablogivi/frontweb:1.1
    ports:
      - "5000:8885" 
    depends_on:
      - sistemasapp
      - backapp

  backapp:
    image: pablogivi/backweb:1.0
    ports: 
      - "8886:8886"
    depends_on:
      - sistemasapp
